sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: qNDO0RApzVeWw0mXGO1d7JXoA1m1UNdcb8Fdo3GDCixJnmxg4Fer8UosQDELPEs3iQCo8JQkeeBB8sDLQMU5ui09KEIp8vg8A6tk6Hmk9VD4mShhUJ1IBR4DcgNRPY4aA7ZHmiG4oDg/AqHNsF7I7dtYe3gXMxwS79A6UxwIKZvAcLuHwZZpM2/C2RC6leNV6nWaFY2QABpVNsuJ/uZ+n5/ncnvEY1rcPg8mGUPlU+lVK2LwHPRNzp9FZhViuALgwRdLJoJkcWAePiL8emYmivKuiLhJrtiZNTA8K/WxhVF7f0ROOpmMHjV3jhIXKNgRJ+Yzc95+dc0i+F6KrB5xdb6vjSI4p6H2W2df1v3lebOEk8QbUCH47fhvWdAK+YcJx/x7e7+FsCUKQjSZ3WIvEhSxxy9sXyUC1Vrq5cNNlLyRZvHODjPbSzypQBW9zgqTr6pS3d3BPnRWC3496X3ZtU3GkgO4U52KsEaJa16TC2bG4EL4EXhyAfkCEVaCMO5sYFhTNwGfbQT3PrmrXBCtpUsL55FVW8/lTfHpdwiPK9w7jXtK/6cjwGOjDbZ9Szxe7sxJiNnqHFEXkmpBg+5ROXheG+MEoIURBzZ+2ktGwmF7ZsdJkGBrY/cFj7PESNnWbhAS7toplYyLaNZq/BEdJawLagSDUeVMg6a3l6A+B6s=
  - secure: O08bVuhWwmfnZIQnrMMkuFtuQ32+4MUIrPQnJBej2VRVV+RwmqkMIz5inrWJBKazTlN3TQmKa26KtfLj8NMCIn7GOa1pXebqSXpXeqbGJX1d/WHae3PQGOw+RWrSJlg4i0a9lamP9V1IMDrpbg/ByehMoKYqdrVV0iRd269k76oD8dT0rO0VTd7IkNlMGZzOP8BZhZK/r+CmU9ibORG5pmqyJrXL2Nlu52icpVuMAfSI15SojhtIbqiqDifGKEbcQnkPhR8v7XxTQa4U3dHz4iZBDm0Tq8y71T1KXDRxak5YdoRGxWNZdxorlO6kVzI86u6cH2Qt0BTlG2XafW0pzcxH4qeluSQIW549bsmkVbiYUxF5639gniVWBBD732PcxDIVYlPD48YhhfpRmrxMTUJVT4ljWt0+SYlkw4cGdIKDnWebsvz6dtt3jAhT7aTgghZKLviFQ85TM4pmkL9oZco26wEw2CrqNdeyB7n90C2OSA6T8ZEhn7lguNjGx/AB+Fz1CG3bU/G1+XqzTr02WXQ0LhYFDPxZAzOab41txfbdhxo70PlYLq1K6vPuCpJPohSFJubUu0t5qYNXzJnx0aPGIoXtvAtsOObeJUbMaI7Gt/25aOtPvs1ax0WFPbGIIOXwUSCapAbV/iOpFkDMo1cRe9NfbzgZvHMSdq3yeUI=
