sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: jiBJYqjoiuUYPOMLVsj08Cojj6SrHNBbkyoRLYwLTHAGma7sdYkGbbSWtCXc56Bq9t9UvBf5MJI8oyvHhm0NX5dxN6g4fYx5F+Qjl2uYx17oD+mmWAzJnEhNmxBp39EUrh21vYz2eO/0OnWYjI+J0qehtMhRTDWFyPjrMev0SIOh4CO1RD8sVK4pWK/eMmRrgjj2el9SeWcX5zypOWFUhqDXELuf5GcTaW5YY5ggOccZkFhI/deVbD2HqF8+xsNqFvpXAJ8NXaU7ZaphruZCctnTfZ325P1S74P8c9yto7aLCLlLVD6auMqk6B2Eg92puZlW5amUS/LD8HK8fCUaYO1GJpwy8qZytJpQStxwQ+gq6oMJ8bmvspZutZGKcmUeKbr/sPBEPNg6HcEC9+e1grUYvGqBN5nl8yhSbUuTTM3WkP3rwPssdueHwMxT11aPwzok54IN7tnioxprHmP44KbBXJHMfSUJKOTmbQKv/7oGvhdj5OZqPM/x76FMh3UMgZhbKrmVV2gkHAotyPDGeBbAMs15j2lRxbwCS15ICrfpZBHwv3xw3ZdKhltPQErGEUDOr4M4oYa23xb66ntW2rmCuMWjI0DjPlTXxXUAaNJ18FBX4KmUDjV/wA/wJ/MXLzAEJrX6xpK1CqZURAZmfyHBM6ivetYH1rQpDod+e7s=
  - secure: dL6JV4zO9BOQDD3Pxb6hRPM6KTBmXUzBxSFWM8VXE/9ahZTez3AROFwXtlt5JXApEo6yeHozhPerrXdNtvPM/LpwZ3pj3zdu10JOVani6lOUbwSHMnxyGFhRuEIO8ZfvodTiJlPOl4DATrEnO5tEDwy3hZjroeOCh9/DsHiSW5aNLLE1ujWP4e8uzSGx50LuYSXVhAkmZkT+YIGYigoKe2mS+eCNd5CfOEiHB0MZQLiMwfDu7oScZdz9fS4/Vp402RsvLhpi/oy5pa9M6AaFSJEVCCqBQUqoajbO5/XJFjoZOImgMCu+kL4/1TCc8jJZDA6/8LJcaPj9VSzuaaASuSwMTRPqYdZ3J3OfGKVM6BT5FkT5yI4vBYUtRoOCxNRE5TMwcAKfMUWBsL5OBDnGIQ8a8P57DGoZ/PwT1AUKuebeOpQjQWSuT0ik+7PFy42W15knS+0MMmUSxHqM+OAi14RbygeSy3jlTobEu/lIOtzXh8eOXI8LeUUp0vaGi+HtGaKxc8FLv3TOWf6m6jFRyMrxioQOZuD8LFn8nIZUJf5/Fg121iuQkvhmr4SDAFZJn7w72qVxqukA0eBd8PzAsEHvuFv814/aVgd9Ue199U7BfirFuuT6ZmcO3YFJXqpFz0RF7O5n/LXd5WpWKTrMFBFo2Vy1YGHxBD+g1u+iu60=
