sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: Cf0ALlhpDbK6PS8fuVlJZ5CrvUiR5fEs7nUH/Vx10mEahTwN8ap3wm07XPd4nns0Df60ai0+c1bHk4UItPItNKOYwOjeauYLPv3WYUvdOUjoZ3KnSi/CLmX0kZDleWFmS4q28CUexZV6LsGQ/n/yg4+0t8zu2X9NVQcTNlDuG15T+/D6f0UAbHpa0aceKgeGxadySmuIEk2+EnRwhWHVIZfg9nR5WdlxZ1VsJZzSphFepIPhcbpOMNuXaJgdkuEEDcQOjZqROsLcl7Xovq7BGiGWsycIw+zxz5X01Jb++PcETzCV8TEW2Jhqw5afEWpd0jW2Gw8GkUNYVPGQnVfgas5jpT2r+io3W3R++3rWDxz+O+B4BOWhtryxDje1ptG63AXD+PoiQGy8aWX4hw56grjxYIq2/lMtv8UDY8zt7BU6G6gTJ/Oox8BIqSdAkpzWr9Gar79cxdsT2wyXv0AcJEUG2qz9cX6kBHxeCo7Xx9hjp5l2nta4r75PA4tryJAa/85g3d6LoWcuLhy80qVK11omKaMTiOgbxYqUZT6mf1ia+HZlcA3/HLe4lnXvkY99nmz5NCEzfKWlNTuqT/Qxax830sgYof1CBYpc/S6Pec/2S4QS6YVCE8W/xbRxC/MUHrmrVXfND/kByvtk+noT4CX8CDYsLcYVD2bdBG0vv3o=
  - secure: FcOasPlTSXqhx42iyrWpMbTfTm1XA3EONO7TOOHaHFXkcsWBgbwHHzQmZLXvnt3dNV/axgNOJFv8oztMOTt7zXmK+IPzc5CGNnbe0ftdRKEz5TtcYbfXp4TKpZAB2MP8zjtukoy450muRhgkqfbEX1LoENaNK54YTWnylP1snS9zgu9CHgcnjwpAL4xVprBnOd3IXIhh6bXu2fATQ8zXpOniaDcZt4oEJcymRyg6uIlDRoNjbAwtJlKSPGOtHHV0x4dcLbXt5GwBqQN8eYIQTErf58QEy2T39f4R8Af3rHAHRLB3XRlGxBvsPUnDTQSw6xkzitJBrwaF0Rz4f8yopk0jRJKz3d3lXf5RYz4BIESg2qrwdY0KDZaeV1xgaR+Z3inYwQHBMF/u8jeAG/YS1OxGIRZj7hpW9xK2YsHlw0BDFD7DvujEoCMXNRMExZ1hBQfq4sCsaG3eRb6A6qH/ylGUc0p0TEW3ed7DKu14/n+0ocCby7OSeR9Orl6MaeueEEePzvD5m//NJ0YqG7n8CVdzfwJ7DLa1Vie9pxvrwSs1aXms7963KXGVg2ytIEWffV0J0x/UWBx3kufLtZWVkX48zNS+zveuxWeNtlzolRcEqRchvZ2nVfCiIFsfilAqM4yMeC6stff30D/RiJzP7Hu5xID5pGojEreK1lgCViU=
