sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: eWrgIzOtr3ixA3iWVck/qyuHaxRZigsUatalxAw3empDfBH7cyvZSLT0SZK5Hb7jK6IBZ3KGc0smtW1gKYqTqsp557HPb5qKRdyrAl/4kVcq4q569jjcRRw0pDJovTlNvHvGu5Lc1ZEBLJ/QNylziwH0gTA8dbJ0KGopvontT8L05XMAIp6xMGUtCVnidQW1j3e3quivUd5/qIFa66i6i/44IXmmzXQ6dBJ6dBJVOaMwouFWy6XlGiF2/lU0VjlIPOUzFd/HuL/rJ1Hk5r3QURUU9SBbWU5SNZ0nyMQOmQAsKCA93ZVL+ipxBWuvdmcwczPXCqi5gWbf1N5U33TwO3IkQ79Wz9JbcW5OMlOxMCjngWx/3NdWKo6EVXzsME5yNit2cdTHUhzSIIaHN8LwPQZSsPeb2/ayt/hemd7m338KgR5Y49K58U2+1KjRPqXT5YB4EgojtAlO+KInjjUBpPmIcTNZ7IReYBAWrvvLKv5wu+xfai/DlsJbskUfho0IF5tInZzLNDS4DMlsLalC1LngIPIw1nbBGlOWfBMBABZ9Ja3mHSKMOb24Rin4SirhAoFovhJHC1oUXTB6mudmG7+r4Y3D2STEzaSaReFsQmNq3CEix8+4F/ty/ALtFx8wlsFhHpToGIxWj2iWS2+voe/iMhYI5VlPIEi7hXwceYw=
  - secure: HLrmnPr1HmT6K8o0MW2+Rg7kx+stRjxA31si2LUy2SS1YfNI9miOuULoMu3IcssAaq2+V4amoJ5ZzVRR54jMbexH2j0kgYeYr/BlJYRlSpAaLW/FHgf1O6k2A3IM0tXG2cgLzIo61Q85HJyXJ5InIB+nfvJNwcfIqhz0rqgnQMxWJqaknYsk6Fv24WyhKNI96n20Stzqh8/F0V5OrjUUIwJvZ4b/FB3Cgz8OpQIlGT7r7s3Nkhx/7ojscFd5jUJaeLSsyhUK+L5bESujrj2ntDGYxCODttQbZBh9mC+jZlTT0quvRUyYuy2dB9t+hWXn8EN4VHAOuIW9RteP4ryaEt5BA1g7JaHDBMNOIDbSgMDsqzmWQ24G2/8oF1VineXSQuBozjKkSgaIDBv7aTBPfhNJDMWvEwnzEd9v198aB+gREy3fZlTouG4Ldi57+NsFt5BpGKpdeY5LDY37di4zpkeh2FcxqHg94YoHVbXG+qYSNmxQs6RgqC95SenqG8mZclw34pRVnTapWc+cRfDNOVedxHjZIVhjGU3ZanTKOScH5qLtyXV7KArGXk7mukX21944aGBhSI6N6lB6Y/hgOzyEySam5DBN1lbfvZV+khSYEpdbnpeqsFTVgL8FM7ugmqOkWQzCZhWjpTRpTNuLoctqRpIaYooV1z0f6E70WGI=
