sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: S5Y7ubOYDiL2FVrmmxM03cr0VIPrJJ/QXIBj46YV/+1ZZVlwv7PU7gcK3DQlwV1qT5CVDLo1Xc8/GqaYqSDunRjBtcZtBkOo9+vdMRwDGR8KkUTEqWK72QcGLKgWJmGU8rOaRwmm+bXcJlvKlX/iKmmV9EeQ/h0LbAYjnY5TPhN96dcTQUzbwHJbiUfHXTpkiJZIyAU4gfgwLqjMH8vySNpcRS+HkEM8ZkwHhEfnSSrfmBs7O4wp0/Aa7AFAcXktovexR0pZJc7FFmjlohx7uI5Yaqqpz1/vSvsO8bLo07Xa4l4MOkfA4RJa2ihP0DmeI5mHljdu9yGIj+7XgNgm0Gg67yPuTiPRmq+Rx0hfbSXr64JxmqhuV2cRooGBsmKzb8IE3X9y5HN4d0fB6I3hI20+wObBbWKQ+FxlGCy4qccEO1SOBfW/+CkzFFVz+W9q4VNHMZtC6sTc1P00jKlXk4ukQtyeMjknJWML3c+F6Tbd44mHjDabpjRZ7J59bG/WZOv6naZsuHXYW9nd7GEhwpbPdRVe+M2O7h7y5Mo4eZtXWVglaZML0c5y5FgHbnLpeYj/LTNZPunrkXjLarw1wfOKVJRhvGIzy4z2SMSRg5IAHYuHcmFvsoBvxMpzrvRSUMqynMbvQ/lsaJftJGeQyUwVbu0UOQ8ugAGkR+AMC0Y=
  - secure: ewXaUSXPJv0ZXlgLuZB8FjI2clQqetNAUTTCr+0vx7Wetwj7m54jXeX27H49oWqpRUOq6D650mDFvS0oAsaKUKl1Q9jsjTg+hH71ZrxgrpVLH3P8bhCmzPcY9RzRwrpTD3BlzdsX8gK325UQCNZBwOv7r/MbVb34C5Vd8x3nP4HqOG8mE+Yseuzfu4gxAS1bgOk8pj65CRadxgAxF1OGOf7i8CZtbj1InS3Li6fgPt23rQzdHUbfoqwN32RZ7UJ58HAhSeF/PmcV+gFD5G8TvgnaBa1HeVzcil4CHTYQM5ZaoZWIo6mO1XrevNJrWmcjfeZFhekT0FtUNOdCQ0vtRFUyT3BRRYou7E9lRtdCfn7qz2ripgqXGVVVa+4PNONU0Jb79DgF7ZpfCwUraQLcFcmWYJDvZzpcR2ThJA+Npi55cBdiXham+av1uFex9arPfo4VMY7odtXFZ17jiGJVHtNw2aWHdni6nfuxHTmTRteiTqHsGMvGxnNvLs7mWVC91THO+ofva9X54TRjOzewc3mkjGKzjR5Q+kJcT18QufUKNG/gdoCL5aAxWopGxPwoYIxxA5R+5dldheqt+8X8K93MGirvyiQG/lR8zZtk6H/xyRyJyxRtZUNxonav7t0GpzoBHbUUsv77bwIjBq76dsV3rxL85HFy+3mz4Wlds7E=
